/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org.index'
import { Route as LogisticsIndexRouteImport } from './routes/logistics.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrgProfileRouteImport } from './routes/org.profile'
import { Route as OrgDocumentsRouteImport } from './routes/org.documents'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminOrganizationsOrgIdRouteImport } from './routes/admin.organizations.$orgId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogisticsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgProfileRoute = OrgProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgRoute,
} as any)
const OrgDocumentsRoute = OrgDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OrgRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrganizationsOrgIdRoute = AdminOrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AdminOrganizationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/logistics': typeof LogisticsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/org/documents': typeof OrgDocumentsRoute
  '/org/profile': typeof OrgProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/org/': typeof OrgIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/org/documents': typeof OrgDocumentsRoute
  '/org/profile': typeof OrgProfileRoute
  '/admin': typeof AdminIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/org': typeof OrgIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/logistics': typeof LogisticsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/org/documents': typeof OrgDocumentsRoute
  '/org/profile': typeof OrgProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/org/': typeof OrgIndexRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/logistics'
    | '/onboarding'
    | '/org'
    | '/sign-in'
    | '/sign-up'
    | '/admin/organizations'
    | '/org/documents'
    | '/org/profile'
    | '/admin/'
    | '/logistics/'
    | '/org/'
    | '/admin/organizations/$orgId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/admin/organizations'
    | '/org/documents'
    | '/org/profile'
    | '/admin'
    | '/logistics'
    | '/org'
    | '/admin/organizations/$orgId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/logistics'
    | '/onboarding'
    | '/org'
    | '/sign-in'
    | '/sign-up'
    | '/admin/organizations'
    | '/org/documents'
    | '/org/profile'
    | '/admin/'
    | '/logistics/'
    | '/org/'
    | '/admin/organizations/$orgId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LogisticsRoute: typeof LogisticsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OrgRoute: typeof OrgRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/'
      fullPath: '/logistics/'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/org/profile': {
      id: '/org/profile'
      path: '/profile'
      fullPath: '/org/profile'
      preLoaderRoute: typeof OrgProfileRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/documents': {
      id: '/org/documents'
      path: '/documents'
      fullPath: '/org/documents'
      preLoaderRoute: typeof OrgDocumentsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations/$orgId': {
      id: '/admin/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/admin/organizations/$orgId'
      preLoaderRoute: typeof AdminOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
  }
}

interface AdminOrganizationsRouteChildren {
  AdminOrganizationsOrgIdRoute: typeof AdminOrganizationsOrgIdRoute
}

const AdminOrganizationsRouteChildren: AdminOrganizationsRouteChildren = {
  AdminOrganizationsOrgIdRoute: AdminOrganizationsOrgIdRoute,
}

const AdminOrganizationsRouteWithChildren =
  AdminOrganizationsRoute._addFileChildren(AdminOrganizationsRouteChildren)

interface AdminRouteChildren {
  AdminOrganizationsRoute: typeof AdminOrganizationsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrganizationsRoute: AdminOrganizationsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LogisticsRouteChildren {
  LogisticsIndexRoute: typeof LogisticsIndexRoute
}

const LogisticsRouteChildren: LogisticsRouteChildren = {
  LogisticsIndexRoute: LogisticsIndexRoute,
}

const LogisticsRouteWithChildren = LogisticsRoute._addFileChildren(
  LogisticsRouteChildren,
)

interface OrgRouteChildren {
  OrgDocumentsRoute: typeof OrgDocumentsRoute
  OrgProfileRoute: typeof OrgProfileRoute
  OrgIndexRoute: typeof OrgIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgDocumentsRoute: OrgDocumentsRoute,
  OrgProfileRoute: OrgProfileRoute,
  OrgIndexRoute: OrgIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LogisticsRoute: LogisticsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OrgRoute: OrgRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
