/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/org.index'
import { Route as LogisticsIndexRouteImport } from './routes/logistics.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrgRequestsRouteImport } from './routes/org.requests'
import { Route as OrgProfileRouteImport } from './routes/org.profile'
import { Route as OrgMarketplaceRouteImport } from './routes/org.marketplace'
import { Route as OrgListingsRouteImport } from './routes/org.listings'
import { Route as OrgInventoryRouteImport } from './routes/org.inventory'
import { Route as OrgDocumentsRouteImport } from './routes/org.documents'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminMedicinesRouteImport } from './routes/admin.medicines'
import { Route as AdminListingsRouteImport } from './routes/admin.listings'
import { Route as OrgRequestsRequestIdRouteImport } from './routes/org.requests.$requestId'
import { Route as OrgMarketplaceListingIdRouteImport } from './routes/org.marketplace.$listingId'
import { Route as OrgListingsNewRouteImport } from './routes/org.listings.new'
import { Route as OrgListingsListingIdRouteImport } from './routes/org.listings.$listingId'
import { Route as OrgInventoryNewRouteImport } from './routes/org.inventory.new'
import { Route as OrgInventoryBatchIdRouteImport } from './routes/org.inventory.$batchId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminRequestsRequestIdRouteImport } from './routes/admin.requests.$requestId'
import { Route as AdminOrganizationsOrgIdRouteImport } from './routes/admin.organizations.$orgId'
import { Route as AdminMedicinesNewRouteImport } from './routes/admin.medicines.new'
import { Route as AdminMedicinesMedicineIdRouteImport } from './routes/admin.medicines.$medicineId'
import { Route as AdminListingsListingIdRouteImport } from './routes/admin.listings.$listingId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const LogisticsIndexRoute = LogisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogisticsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrgRequestsRoute = OrgRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OrgRoute,
} as any)
const OrgProfileRoute = OrgProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrgRoute,
} as any)
const OrgMarketplaceRoute = OrgMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => OrgRoute,
} as any)
const OrgListingsRoute = OrgListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => OrgRoute,
} as any)
const OrgInventoryRoute = OrgInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OrgRoute,
} as any)
const OrgDocumentsRoute = OrgDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OrgRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedicinesRoute = AdminMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListingsRoute = AdminListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AdminRoute,
} as any)
const OrgRequestsRequestIdRoute = OrgRequestsRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => OrgRequestsRoute,
} as any)
const OrgMarketplaceListingIdRoute = OrgMarketplaceListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => OrgMarketplaceRoute,
} as any)
const OrgListingsNewRoute = OrgListingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrgListingsRoute,
} as any)
const OrgListingsListingIdRoute = OrgListingsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => OrgListingsRoute,
} as any)
const OrgInventoryNewRoute = OrgInventoryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrgInventoryRoute,
} as any)
const OrgInventoryBatchIdRoute = OrgInventoryBatchIdRouteImport.update({
  id: '/$batchId',
  path: '/$batchId',
  getParentRoute: () => OrgInventoryRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRequestsRequestIdRoute = AdminRequestsRequestIdRouteImport.update({
  id: '/$requestId',
  path: '/$requestId',
  getParentRoute: () => AdminRequestsRoute,
} as any)
const AdminOrganizationsOrgIdRoute = AdminOrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AdminOrganizationsRoute,
} as any)
const AdminMedicinesNewRoute = AdminMedicinesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminMedicinesRoute,
} as any)
const AdminMedicinesMedicineIdRoute =
  AdminMedicinesMedicineIdRouteImport.update({
    id: '/$medicineId',
    path: '/$medicineId',
    getParentRoute: () => AdminMedicinesRoute,
  } as any)
const AdminListingsListingIdRoute = AdminListingsListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => AdminListingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/logistics': typeof LogisticsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/medicines': typeof AdminMedicinesRouteWithChildren
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/org/documents': typeof OrgDocumentsRoute
  '/org/inventory': typeof OrgInventoryRouteWithChildren
  '/org/listings': typeof OrgListingsRouteWithChildren
  '/org/marketplace': typeof OrgMarketplaceRouteWithChildren
  '/org/profile': typeof OrgProfileRoute
  '/org/requests': typeof OrgRequestsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/org/': typeof OrgIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/medicines/$medicineId': typeof AdminMedicinesMedicineIdRoute
  '/admin/medicines/new': typeof AdminMedicinesNewRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/inventory/$batchId': typeof OrgInventoryBatchIdRoute
  '/org/inventory/new': typeof OrgInventoryNewRoute
  '/org/listings/$listingId': typeof OrgListingsListingIdRoute
  '/org/listings/new': typeof OrgListingsNewRoute
  '/org/marketplace/$listingId': typeof OrgMarketplaceListingIdRoute
  '/org/requests/$requestId': typeof OrgRequestsRequestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/onboarding': typeof OnboardingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/medicines': typeof AdminMedicinesRouteWithChildren
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/org/documents': typeof OrgDocumentsRoute
  '/org/inventory': typeof OrgInventoryRouteWithChildren
  '/org/listings': typeof OrgListingsRouteWithChildren
  '/org/marketplace': typeof OrgMarketplaceRouteWithChildren
  '/org/profile': typeof OrgProfileRoute
  '/org/requests': typeof OrgRequestsRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/logistics': typeof LogisticsIndexRoute
  '/org': typeof OrgIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/medicines/$medicineId': typeof AdminMedicinesMedicineIdRoute
  '/admin/medicines/new': typeof AdminMedicinesNewRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/inventory/$batchId': typeof OrgInventoryBatchIdRoute
  '/org/inventory/new': typeof OrgInventoryNewRoute
  '/org/listings/$listingId': typeof OrgListingsListingIdRoute
  '/org/listings/new': typeof OrgListingsNewRoute
  '/org/marketplace/$listingId': typeof OrgMarketplaceListingIdRoute
  '/org/requests/$requestId': typeof OrgRequestsRequestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/logistics': typeof LogisticsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/listings': typeof AdminListingsRouteWithChildren
  '/admin/medicines': typeof AdminMedicinesRouteWithChildren
  '/admin/organizations': typeof AdminOrganizationsRouteWithChildren
  '/admin/requests': typeof AdminRequestsRouteWithChildren
  '/org/documents': typeof OrgDocumentsRoute
  '/org/inventory': typeof OrgInventoryRouteWithChildren
  '/org/listings': typeof OrgListingsRouteWithChildren
  '/org/marketplace': typeof OrgMarketplaceRouteWithChildren
  '/org/profile': typeof OrgProfileRoute
  '/org/requests': typeof OrgRequestsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/logistics/': typeof LogisticsIndexRoute
  '/org/': typeof OrgIndexRoute
  '/admin/listings/$listingId': typeof AdminListingsListingIdRoute
  '/admin/medicines/$medicineId': typeof AdminMedicinesMedicineIdRoute
  '/admin/medicines/new': typeof AdminMedicinesNewRoute
  '/admin/organizations/$orgId': typeof AdminOrganizationsOrgIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/org/inventory/$batchId': typeof OrgInventoryBatchIdRoute
  '/org/inventory/new': typeof OrgInventoryNewRoute
  '/org/listings/$listingId': typeof OrgListingsListingIdRoute
  '/org/listings/new': typeof OrgListingsNewRoute
  '/org/marketplace/$listingId': typeof OrgMarketplaceListingIdRoute
  '/org/requests/$requestId': typeof OrgRequestsRequestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/logistics'
    | '/onboarding'
    | '/org'
    | '/sign-in'
    | '/sign-up'
    | '/admin/listings'
    | '/admin/medicines'
    | '/admin/organizations'
    | '/admin/requests'
    | '/org/documents'
    | '/org/inventory'
    | '/org/listings'
    | '/org/marketplace'
    | '/org/profile'
    | '/org/requests'
    | '/admin/'
    | '/logistics/'
    | '/org/'
    | '/admin/listings/$listingId'
    | '/admin/medicines/$medicineId'
    | '/admin/medicines/new'
    | '/admin/organizations/$orgId'
    | '/admin/requests/$requestId'
    | '/api/auth/$'
    | '/org/inventory/$batchId'
    | '/org/inventory/new'
    | '/org/listings/$listingId'
    | '/org/listings/new'
    | '/org/marketplace/$listingId'
    | '/org/requests/$requestId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/sign-in'
    | '/sign-up'
    | '/admin/listings'
    | '/admin/medicines'
    | '/admin/organizations'
    | '/admin/requests'
    | '/org/documents'
    | '/org/inventory'
    | '/org/listings'
    | '/org/marketplace'
    | '/org/profile'
    | '/org/requests'
    | '/admin'
    | '/logistics'
    | '/org'
    | '/admin/listings/$listingId'
    | '/admin/medicines/$medicineId'
    | '/admin/medicines/new'
    | '/admin/organizations/$orgId'
    | '/admin/requests/$requestId'
    | '/api/auth/$'
    | '/org/inventory/$batchId'
    | '/org/inventory/new'
    | '/org/listings/$listingId'
    | '/org/listings/new'
    | '/org/marketplace/$listingId'
    | '/org/requests/$requestId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/logistics'
    | '/onboarding'
    | '/org'
    | '/sign-in'
    | '/sign-up'
    | '/admin/listings'
    | '/admin/medicines'
    | '/admin/organizations'
    | '/admin/requests'
    | '/org/documents'
    | '/org/inventory'
    | '/org/listings'
    | '/org/marketplace'
    | '/org/profile'
    | '/org/requests'
    | '/admin/'
    | '/logistics/'
    | '/org/'
    | '/admin/listings/$listingId'
    | '/admin/medicines/$medicineId'
    | '/admin/medicines/new'
    | '/admin/organizations/$orgId'
    | '/admin/requests/$requestId'
    | '/api/auth/$'
    | '/org/inventory/$batchId'
    | '/org/inventory/new'
    | '/org/listings/$listingId'
    | '/org/listings/new'
    | '/org/marketplace/$listingId'
    | '/org/requests/$requestId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LogisticsRoute: typeof LogisticsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OrgRoute: typeof OrgRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org/': {
      id: '/org/'
      path: '/'
      fullPath: '/org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/logistics/': {
      id: '/logistics/'
      path: '/'
      fullPath: '/logistics/'
      preLoaderRoute: typeof LogisticsIndexRouteImport
      parentRoute: typeof LogisticsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/org/requests': {
      id: '/org/requests'
      path: '/requests'
      fullPath: '/org/requests'
      preLoaderRoute: typeof OrgRequestsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/profile': {
      id: '/org/profile'
      path: '/profile'
      fullPath: '/org/profile'
      preLoaderRoute: typeof OrgProfileRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/marketplace': {
      id: '/org/marketplace'
      path: '/marketplace'
      fullPath: '/org/marketplace'
      preLoaderRoute: typeof OrgMarketplaceRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/listings': {
      id: '/org/listings'
      path: '/listings'
      fullPath: '/org/listings'
      preLoaderRoute: typeof OrgListingsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/inventory': {
      id: '/org/inventory'
      path: '/inventory'
      fullPath: '/org/inventory'
      preLoaderRoute: typeof OrgInventoryRouteImport
      parentRoute: typeof OrgRoute
    }
    '/org/documents': {
      id: '/org/documents'
      path: '/documents'
      fullPath: '/org/documents'
      preLoaderRoute: typeof OrgDocumentsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medicines': {
      id: '/admin/medicines'
      path: '/medicines'
      fullPath: '/admin/medicines'
      preLoaderRoute: typeof AdminMedicinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listings': {
      id: '/admin/listings'
      path: '/listings'
      fullPath: '/admin/listings'
      preLoaderRoute: typeof AdminListingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/org/requests/$requestId': {
      id: '/org/requests/$requestId'
      path: '/$requestId'
      fullPath: '/org/requests/$requestId'
      preLoaderRoute: typeof OrgRequestsRequestIdRouteImport
      parentRoute: typeof OrgRequestsRoute
    }
    '/org/marketplace/$listingId': {
      id: '/org/marketplace/$listingId'
      path: '/$listingId'
      fullPath: '/org/marketplace/$listingId'
      preLoaderRoute: typeof OrgMarketplaceListingIdRouteImport
      parentRoute: typeof OrgMarketplaceRoute
    }
    '/org/listings/new': {
      id: '/org/listings/new'
      path: '/new'
      fullPath: '/org/listings/new'
      preLoaderRoute: typeof OrgListingsNewRouteImport
      parentRoute: typeof OrgListingsRoute
    }
    '/org/listings/$listingId': {
      id: '/org/listings/$listingId'
      path: '/$listingId'
      fullPath: '/org/listings/$listingId'
      preLoaderRoute: typeof OrgListingsListingIdRouteImport
      parentRoute: typeof OrgListingsRoute
    }
    '/org/inventory/new': {
      id: '/org/inventory/new'
      path: '/new'
      fullPath: '/org/inventory/new'
      preLoaderRoute: typeof OrgInventoryNewRouteImport
      parentRoute: typeof OrgInventoryRoute
    }
    '/org/inventory/$batchId': {
      id: '/org/inventory/$batchId'
      path: '/$batchId'
      fullPath: '/org/inventory/$batchId'
      preLoaderRoute: typeof OrgInventoryBatchIdRouteImport
      parentRoute: typeof OrgInventoryRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/$requestId': {
      id: '/admin/requests/$requestId'
      path: '/$requestId'
      fullPath: '/admin/requests/$requestId'
      preLoaderRoute: typeof AdminRequestsRequestIdRouteImport
      parentRoute: typeof AdminRequestsRoute
    }
    '/admin/organizations/$orgId': {
      id: '/admin/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/admin/organizations/$orgId'
      preLoaderRoute: typeof AdminOrganizationsOrgIdRouteImport
      parentRoute: typeof AdminOrganizationsRoute
    }
    '/admin/medicines/new': {
      id: '/admin/medicines/new'
      path: '/new'
      fullPath: '/admin/medicines/new'
      preLoaderRoute: typeof AdminMedicinesNewRouteImport
      parentRoute: typeof AdminMedicinesRoute
    }
    '/admin/medicines/$medicineId': {
      id: '/admin/medicines/$medicineId'
      path: '/$medicineId'
      fullPath: '/admin/medicines/$medicineId'
      preLoaderRoute: typeof AdminMedicinesMedicineIdRouteImport
      parentRoute: typeof AdminMedicinesRoute
    }
    '/admin/listings/$listingId': {
      id: '/admin/listings/$listingId'
      path: '/$listingId'
      fullPath: '/admin/listings/$listingId'
      preLoaderRoute: typeof AdminListingsListingIdRouteImport
      parentRoute: typeof AdminListingsRoute
    }
  }
}

interface AdminListingsRouteChildren {
  AdminListingsListingIdRoute: typeof AdminListingsListingIdRoute
}

const AdminListingsRouteChildren: AdminListingsRouteChildren = {
  AdminListingsListingIdRoute: AdminListingsListingIdRoute,
}

const AdminListingsRouteWithChildren = AdminListingsRoute._addFileChildren(
  AdminListingsRouteChildren,
)

interface AdminMedicinesRouteChildren {
  AdminMedicinesMedicineIdRoute: typeof AdminMedicinesMedicineIdRoute
  AdminMedicinesNewRoute: typeof AdminMedicinesNewRoute
}

const AdminMedicinesRouteChildren: AdminMedicinesRouteChildren = {
  AdminMedicinesMedicineIdRoute: AdminMedicinesMedicineIdRoute,
  AdminMedicinesNewRoute: AdminMedicinesNewRoute,
}

const AdminMedicinesRouteWithChildren = AdminMedicinesRoute._addFileChildren(
  AdminMedicinesRouteChildren,
)

interface AdminOrganizationsRouteChildren {
  AdminOrganizationsOrgIdRoute: typeof AdminOrganizationsOrgIdRoute
}

const AdminOrganizationsRouteChildren: AdminOrganizationsRouteChildren = {
  AdminOrganizationsOrgIdRoute: AdminOrganizationsOrgIdRoute,
}

const AdminOrganizationsRouteWithChildren =
  AdminOrganizationsRoute._addFileChildren(AdminOrganizationsRouteChildren)

interface AdminRequestsRouteChildren {
  AdminRequestsRequestIdRoute: typeof AdminRequestsRequestIdRoute
}

const AdminRequestsRouteChildren: AdminRequestsRouteChildren = {
  AdminRequestsRequestIdRoute: AdminRequestsRequestIdRoute,
}

const AdminRequestsRouteWithChildren = AdminRequestsRoute._addFileChildren(
  AdminRequestsRouteChildren,
)

interface AdminRouteChildren {
  AdminListingsRoute: typeof AdminListingsRouteWithChildren
  AdminMedicinesRoute: typeof AdminMedicinesRouteWithChildren
  AdminOrganizationsRoute: typeof AdminOrganizationsRouteWithChildren
  AdminRequestsRoute: typeof AdminRequestsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminListingsRoute: AdminListingsRouteWithChildren,
  AdminMedicinesRoute: AdminMedicinesRouteWithChildren,
  AdminOrganizationsRoute: AdminOrganizationsRouteWithChildren,
  AdminRequestsRoute: AdminRequestsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LogisticsRouteChildren {
  LogisticsIndexRoute: typeof LogisticsIndexRoute
}

const LogisticsRouteChildren: LogisticsRouteChildren = {
  LogisticsIndexRoute: LogisticsIndexRoute,
}

const LogisticsRouteWithChildren = LogisticsRoute._addFileChildren(
  LogisticsRouteChildren,
)

interface OrgInventoryRouteChildren {
  OrgInventoryBatchIdRoute: typeof OrgInventoryBatchIdRoute
  OrgInventoryNewRoute: typeof OrgInventoryNewRoute
}

const OrgInventoryRouteChildren: OrgInventoryRouteChildren = {
  OrgInventoryBatchIdRoute: OrgInventoryBatchIdRoute,
  OrgInventoryNewRoute: OrgInventoryNewRoute,
}

const OrgInventoryRouteWithChildren = OrgInventoryRoute._addFileChildren(
  OrgInventoryRouteChildren,
)

interface OrgListingsRouteChildren {
  OrgListingsListingIdRoute: typeof OrgListingsListingIdRoute
  OrgListingsNewRoute: typeof OrgListingsNewRoute
}

const OrgListingsRouteChildren: OrgListingsRouteChildren = {
  OrgListingsListingIdRoute: OrgListingsListingIdRoute,
  OrgListingsNewRoute: OrgListingsNewRoute,
}

const OrgListingsRouteWithChildren = OrgListingsRoute._addFileChildren(
  OrgListingsRouteChildren,
)

interface OrgMarketplaceRouteChildren {
  OrgMarketplaceListingIdRoute: typeof OrgMarketplaceListingIdRoute
}

const OrgMarketplaceRouteChildren: OrgMarketplaceRouteChildren = {
  OrgMarketplaceListingIdRoute: OrgMarketplaceListingIdRoute,
}

const OrgMarketplaceRouteWithChildren = OrgMarketplaceRoute._addFileChildren(
  OrgMarketplaceRouteChildren,
)

interface OrgRequestsRouteChildren {
  OrgRequestsRequestIdRoute: typeof OrgRequestsRequestIdRoute
}

const OrgRequestsRouteChildren: OrgRequestsRouteChildren = {
  OrgRequestsRequestIdRoute: OrgRequestsRequestIdRoute,
}

const OrgRequestsRouteWithChildren = OrgRequestsRoute._addFileChildren(
  OrgRequestsRouteChildren,
)

interface OrgRouteChildren {
  OrgDocumentsRoute: typeof OrgDocumentsRoute
  OrgInventoryRoute: typeof OrgInventoryRouteWithChildren
  OrgListingsRoute: typeof OrgListingsRouteWithChildren
  OrgMarketplaceRoute: typeof OrgMarketplaceRouteWithChildren
  OrgProfileRoute: typeof OrgProfileRoute
  OrgRequestsRoute: typeof OrgRequestsRouteWithChildren
  OrgIndexRoute: typeof OrgIndexRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgDocumentsRoute: OrgDocumentsRoute,
  OrgInventoryRoute: OrgInventoryRouteWithChildren,
  OrgListingsRoute: OrgListingsRouteWithChildren,
  OrgMarketplaceRoute: OrgMarketplaceRouteWithChildren,
  OrgProfileRoute: OrgProfileRoute,
  OrgRequestsRoute: OrgRequestsRouteWithChildren,
  OrgIndexRoute: OrgIndexRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LogisticsRoute: LogisticsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OrgRoute: OrgRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
